# Site settings
title: Nobody's personal site
email: az8321550@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey guys. My name is Body No. This is my blog. Build by jekyll.
  Since I was young. I liked play computer game.
  And wondering how the game created.
  I had mass interested at it.
  Then when I was 18 years old.
  I began coding.
  A computer engineer.
  Because I like it. Just do it. No regret.

gems: [jekyll-paginate]
paginate: 10
paginate_path: "/page:num"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://az8321550.github.io" # the base hostname & protocol for your site
twitter_username: az8321550
github_username:  az8321550

# Build settings
markdown: kramdown
