name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: go ssh and build
      uses: appleboy/ssh-action@v0.0.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script_stop: true
        script: |
          cd /home/code/bodyno.github.io/_site
          git pull
          docker run --rm \
            --volume="$PWD:/srv/jekyll:Z" \
            -it jekyll/jekyll:3.8 \
            jekyll build
