name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: go ssh and build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script_stop: true
        script: |
          cd /home/code/bodyno.github.io
          git pull
          docker run --rm --volume="$PWD:/srv/jekyll:Z" jekyll/jekyll:3.8 jekyll build
